---
#- Deploy application -#
#- Prepare all nodes -#
- name: Apply common configuration to all nodes
  hosts: all
  remote_user: vitaliy.tsutsman

  roles:
    - { role: common, when: "ansible_os_family == 'RedHat'" }

#- Prepare all main -#
- name: Apply configuration to main server
  hosts: main-servers
  remote_user: vitaliy.tsutsman

  roles:
    - { role: main, when: "ansible_os_family == 'RedHat'" }

#- Prepare all database servers -#
- name: Apply configuration to database servers
  hosts: db-servers
  remote_user: vitaliy.tsutsman

  roles:
    - { role: db, when: "ansible_os_family == 'RedHat'" }

#- Prepare all back-end servers -#
- name: Apply configuration to back-end servers
  hosts: music-servers
  remote_user: vitaliy.tsutsman

  roles:
    - { role: music, when: "ansible_os_family == 'RedHat'" }
