---
# Add Docker repository

- name: Add docker repos
  yum_repository:
    name: docker
    state: present
    description: Docker stable repos
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Update cache
  yum:
    update_cache: yes

- name: Install docker
  yum:
    name: docker-ce
    state: present

